<#
.SYNOPSIS
    Publishes MaxDpsCompanion.exe into dist\.
.DESCRIPTION
    Kills any running copy first (a locked exe would silently leave the old
    bytes in place), stamps the build version, and publishes.
    Fails loudly if the output is not fresh.
#>
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

$project = Join-Path $PSScriptRoot 'app\MaxDpsCompanion\MaxDpsCompanion.csproj'
$genDir  = 'app\MaxDpsCompanion'
$output  = Join-Path $PSScriptRoot 'dist'

# 1. Kill any running copy — otherwise publish cannot replace the exe and the
# old build silently survives.
$procs = Get-Process -Name MaxDpsCompanion -ErrorAction SilentlyContinue
foreach ($p in $procs) {
    Write-Host "Stopping running copy (PID $($p.Id))..."
    Stop-Process -Id $p.Id -Force
}
Start-Sleep -Seconds 2

# 2. Stamp the version from git (commit + time) so the title bar can prove
# which build is running.
$commit = 'dev'
try { $commit = (git rev-parse --short HEAD 2>$null).Trim() } catch { }
if ([string]::IsNullOrWhiteSpace($commit)) { $commit = 'dev' }
$stamp = Get-Date -Format 'yyyy-MM-dd HH:mm'
$genPath = Join-Path $PSScriptRoot "$genDir\ThisAssembly.Gen.cs"
$genContent = @"
// <auto-generated> — written by build.ps1. Do not edit by hand.
namespace MaxDpsCompanion;

internal static partial class ThisAssemblyGen
{
    internal const string GitCommit = "$commit";
    internal const string BuildTime = "$stamp";
}
"@
Set-Content -LiteralPath $genPath -Value $genContent -Encoding UTF8

# 3. Clean dist so stale files can never masquerade as a fresh publish.
# Preserve .gitkeep so the folder stays tracked.
$keep = Join-Path $output '.gitkeep'
if (-not (Test-Path $output)) { New-Item -ItemType Directory -Path $output | Out-Null }
Get-ChildItem -LiteralPath $output -Force | Where-Object { $_.Name -ne '.gitkeep' } | Remove-Item -Recurse -Force

$arguments = @(
    'publish', $project,
    '-c', 'Release',
    '-r', 'win-x64',
    '-o', $output,
    '-p:SelfContained=false',
    '-p:PublishSingleFile=true'
)

& dotnet @arguments
if ($LASTEXITCODE -ne 0) { throw "dotnet publish failed with exit code $LASTEXITCODE" }

$exe = Join-Path $output 'MaxDpsCompanion.exe'
if (-not (Test-Path $exe)) { throw "publish produced no exe at $exe" }
$age = (Get-Date) - (Get-Item $exe).LastWriteTime
if ($age.TotalMinutes -gt 5) { throw "published exe is stale ($($age.TotalMinutes.ToString('0')) min old) — publish did not replace it" }

$defaultSettings = Join-Path $PSScriptRoot 'settings.ini'
$distSettings = Join-Path $output 'settings.ini'
if ((Test-Path $defaultSettings) -and (-not (Test-Path $distSettings))) {
    Copy-Item -LiteralPath $defaultSettings -Destination $distSettings -Force
    Write-Host "Copied default settings.ini (existing dist copy preserved on rebuilds)."
}
if (-not (Test-Path $keep)) { Set-Content -LiteralPath $keep -Value '' -Encoding UTF8 }

Write-Host "Published to $output (commit $commit, $stamp)"
Get-ChildItem -LiteralPath $output | Select-Object Name, Length, LastWriteTime
