// <auto-generated> — written by build.ps1. Do not edit by hand.
namespace MaxDpsCompanion;

internal static partial class ThisAssemblyGen
{
    internal const string GitCommit = "73680d4";
    internal const string BuildTime = "2026-10-10 15:48";
}
