// <auto-generated> — written by build.ps1. Do not edit by hand.
namespace MaxDpsCompanion;

internal static partial class ThisAssemblyGen
{
    internal const string GitCommit = "e6aaed4";
    internal const string BuildTime = "2026-09-10 14:12";
}
