// <auto-generated> — written by build.ps1. Do not edit by hand.
namespace MaxDpsCompanion;

internal static partial class ThisAssemblyGen
{
    internal const string GitCommit = "7cf7f63";
    internal const string BuildTime = "2026-09-22 10:59";
}
