# Extracts the authoritative ability categories from the pinned MaxDps vendor
# snapshot into JSON for the Companion ability knowledge catalog.
#
#   vendor/MaxDps/Cooldowns.lua
#     ns.classCooldowns[CLASS][SPEC] = { offensive = {...}, defensive = {...} }
#     ns.classInterrupts[CLASS][SPEC] = { ["Name"] = id, ... }
#
# Output: app/MaxDpsCompanion/Knowledge/vendor-abilities.json
#
# The vendor snapshot is READ-ONLY input. This script never writes to vendor/.
# Run from the repository root:
#   pwsh -File tools/Extract-VendorAbilities.ps1

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$luaPath = Join-Path $root 'vendor/MaxDps/Cooldowns.lua'
$outPath = Join-Path $root 'app/MaxDpsCompanion/Knowledge/vendor-abilities.json'

if (-not (Test-Path -LiteralPath $luaPath)) {
    throw "vendor Cooldowns.lua not found at $luaPath"
}

$lines = Get-Content -LiteralPath $luaPath
$entries = New-Object System.Collections.Generic.List[object]

$mode = ''       # '', 'cooldowns', 'interrupts'
$class = ''
$spec = ''
$bucket = ''

foreach ($raw in $lines) {
    $line = $raw.TrimEnd()

    if ($line -match '^ns\.classCooldowns\s*=\s*\{\s*$') { $mode = 'cooldowns'; $class=''; $spec=''; $bucket=''; continue }
    if ($line -match '^ns\.classInterrupts\s*=\s*\{\s*$') { $mode = 'interrupts'; $class=''; $spec=''; $bucket=''; continue }
    if ($mode -eq '' -and $line -match '^\}\s*$') { continue }

    # class: 4-space indent, UPPERCASE token, ends with `= {`
    if ($line -match '^\s{4}([A-Z]+)\s*=\s*\{\s*$') { $class = $Matches[1]; $spec=''; $bucket=''; continue }
    # bucket keys (cooldowns only): 12-space indent
    if ($line -match '^\s{12}(offensive|defensive)\s*=\s*\{\s*$') { $bucket = $Matches[1]; continue }
    # spec keys: 8-space indent, either bare or ["Quoted Name"]
    if ($line -match '^\s{8}(\["(?<q>[^"]+)"\]|(?<b>[A-Za-z_][A-Za-z0-9_]*))\s*=\s*\{\s*$') {
        if ($Matches['q']) { $spec = $Matches['q'] } else { $spec = $Matches['b'] }
        $bucket = ''
        continue
    }
    # ability entry: 16-space indent in classCooldowns, 12-space in classInterrupts
    if ($mode -ne '' -and $line -match '^\s{12,16}\["(?<name>[^"]+)"\]\s*=\s*(?<id>\d+)\s*,') {
        $category =
            if ($mode -eq 'interrupts') { 'Interrupt' }
            elseif ($bucket -eq 'defensive') { 'Defensive' }
            elseif ($bucket -eq 'offensive') { 'Offensive' }
            else { '' }
        if ($category -ne '' -and $class -ne '' -and $spec -ne '') {
            $entries.Add([pscustomobject]@{
                class = $class
                spec = $spec
                category = $category
                name = $Matches['name']
                id = [int]$Matches['id']
            })
        }
        continue
    }
}

# Deduplicate on (class, spec, category, name) keeping the lowest id.
$dedup = @{}
$order = New-Object System.Collections.Generic.List[string]
foreach ($e in $entries) {
    $key = "$($e.class)|$($e.spec)|$($e.category)|$($e.name)"
    if ($dedup.ContainsKey($key)) {
        if ($e.id -lt $dedup[$key].id) { $dedup[$key] = $e }
    } else {
        $dedup[$key] = $e
        $order.Add($key)
    }
}

$sorted = $order | ForEach-Object { $dedup[$_] } | Sort-Object class, spec, category, name

$doc = [pscustomobject]@{
    generatedFrom = 'vendor/MaxDps/Cooldowns.lua'
    note = 'Generated by tools/Extract-VendorAbilities.ps1 - do not hand-edit; regenerate when the vendor pin changes.'
    entries = @($sorted)
}

$dir = Split-Path -Parent $outPath
if (-not (Test-Path -LiteralPath $dir)) { New-Item -ItemType Directory -Path $dir | Out-Null }
$json = $doc | ConvertTo-Json -Depth 5
[System.IO.File]::WriteAllText($outPath, $json)

$byCategory = $entries | Group-Object category | Sort-Object Name
"Wrote $($sorted.Count) entries to $outPath"
$byCategory | ForEach-Object { "  $($_.Name): $($_.Count)" }
$byClass = ($entries | Select-Object -ExpandProperty class -Unique).Count
"Classes: $byClass"
